services:
  mongodb:
    image: mongo:latest
    container_name: ms-client-mongodb    
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db      
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    networks:
      - ms-client-network
    
volumes:
  mongodb-data:
    driver: local

networks:
  ms-client-network:
    driver: bridge
    name: ms-client-network